# Generated by Django 5.2 on 2025-10-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='discount_precent',
            new_name='discount_percent',
        ),
    ]
